%YAML 1.3
---
- MouseGesture: ''
- KeyPress:
  - Super_L
  - click
...
---
- Key: [Smart Shift, pressed]
- KeyPress:
  - [Control_L, Shift_L, M]
  - click
...
---
- Key: [Back Button, pressed]
- KeyPress:
  - [Super_L, Page_Down]
  - click
...
---
- Key: [Forward Button, pressed]
- KeyPress:
  - [Super_L, Page_Up]
  - click
...
---
- Test: [thumb_wheel_up, 0xa]
- KeyPress:
  - XF86_AudioLowerVolume
  - click
...
---
- Test: [thumb_wheel_down, 0xa]
- KeyPress:
  - XF86_AudioRaiseVolume
  - click
...
