%YAML 1.3
---
- Test: [thumb_wheel_up, 10]
- KeyPress:
  - XF86_AudioRaiseVolume
  - click
...
---
- Test: [thumb_wheel_down, 10]
- KeyPress:
  - XF86_AudioLowerVolume
  - click
...
---
- Key: [Back Button, pressed]
- KeyPress:
  - [Super_L, Page_Down]
  - click
...
---
- Key: [Forward Button, pressed]
- KeyPress:
  - [Super_L, Page_Up]
  - click
...
